### ISSUE TITLE
开屏广告对上海农商银行app无效

### ISSUE THREAD

**Issue by free-diy** [MengNianxiaoyao/gkd-subscription#69]
https://i.gkd.li/i/15491928

开屏广告对这个app没有作用，试了其他大佬的订阅也都没有用，请大佬看看能解决这个问题伐

**Comment by MengNianxiaoyao** [comment]
已添加，更新后试试

**Comment by free-diy** [comment]
> 已添加，更新后试试

这个app比较怪，你添加的规则是有时能跳过，有时失效。
AIsouler那里我也咨询了，也没解决。
https://github.com/AIsouler/GKD_subscription/issues/228

**Comment by MengNianxiaoyao** [comment]
> > 已添加，更新后试试
> 
> 这个app比较怪，你添加的规则是有时能跳过，有时失效。 AIsouler那里我也咨询了，也没解决。 [AIsouler/GKD_subscription#228](https://github.com/AIsouler/GKD_subscription/issues/228)

可能普通点击有时点不了，下次版本更新改一下

**Comment by free-diy** [comment]
> > > 已添加，更新后试试
> > 
> > 
> > 这个app比较怪，你添加的规则是有时能跳过，有时失效。 AIsouler那里我也咨询了，也没解决。 [AIsouler/GKD_subscription#228](https://github.com/AIsouler/GKD_subscription/issues/228)
> 
> 可能普通点击有时点不了，下次版本更新改一下

刚升级到v36版本了，还是不行。 建议大佬下个这个app测试下

**Comment by MengNianxiaoyao** [comment]
要不你更新下gkd吧，试试gkd最新版

**Comment by AIsouler** [comment]
无解，建议卸载

**Comment by free-diy** [comment]
> 无解，建议卸载

不能卸载啊，这个银行卡是我工资卡。
