### ISSUE TITLE
百度地图启动广告

### ISSUE THREAD

**Issue by sam0773** [MengNianxiaoyao/gkd-subscription#77]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/MengNianxiaoyao/gkd-subscription) 导致的

- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue
- [X] 我确保提供 误触/不执行规则 的界面的快照, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/15801034
开屏广告不会触发跳过

**Comment by MengNianxiaoyao** [comment]
已经触发，但点击无效

**Comment by sam0773** [comment]
这是一封自动回复邮件你好，您所发的邮件我已收到，我将在阅读后尽快给你回复。

**Comment by sam0773** [comment]
再测试了一下…不进行任何操作，打开app在广告倒计时结束后，会有GKD的跳过提示。如果手动点右上角跳过，可以立即跳过广告…看看是否还能优化一下…

**Comment by MengNianxiaoyao** [comment]
> 再测试了一下…不进行任何操作，打开app在广告倒计时结束后，会有GKD的跳过提示。如果手动点右上角跳过，可以立即跳过广告…看看是否还能优化一下…

添加了app的开屏广告规则，更新后打开试试。个人感觉也是不行，可能app不响应gkd的点击

**Comment by sam0773** [comment]
已测试…GKD弹窗比之前早了，但是确实好像是毫无用处…看来百度确实毒瘤了…
